name: バグ報告
description: バグや不具合の報告
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 概要
      description: バグの内容を説明してください
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 再現手順
      description: バグを再現する手順
      placeholder: |
        1. `jpfs simulate ...` を実行
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: jpfs バージョン
      placeholder: "0.3.0"
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python バージョン
      placeholder: "3.14.0"
    validations:
      required: true
